version: "1"

volumes:
  db_data:
    driver: local


services:
  db:
    image: postgres:15.1-alpine
    container_name: postgres_banking
    ports:
      - "5437:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

